---
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
sudo: false
branches:
  only:
    - master
install: pip install -U -r test-requirements.txt
script: ./test.sh
after_success: coveralls
